#!/bin/bash
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A  83/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   LYS A  83/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A  83/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A  83/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   LYS A  83/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A  83/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A  83/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A  83/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   CYS A 275/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   CYS A 275/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   CYS A 275/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   CYS A 275/g" pdb
sed -i "0,/ S   ???     1/s/ S   ???     1/ S   CYS A 275/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   THR A 335/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   THR A 335/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   THR A 335/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   THR A 335/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   THR A 335/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   THR A 335/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   PRO A 338/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   PRO A 338/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   PRO A 338/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   PRO A 338/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   PRO A 338/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   PRO A 338/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ARG A 339/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 339/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A 361/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   LYS A 361/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A 361/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A 361/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   LYS A 361/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A 361/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A 361/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   LYS A 361/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   HIS A 423/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   HIS A 423/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   HIS A 423/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   HIS A 423/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   HIS A 423/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   HIS A 423/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   HIS A 423/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   HIS A 423/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   HIS A 423/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ S   ???     1/s/ S   ???     1/ S   FEV A 502/g" pdb
sed -i "0,/FE   ???     1/s/FE   ???     1/FE   FEV A 502/g" pdb
sed -i "0,/FE   ???     1/s/FE   ???     1/FE   FEV A 502/g" pdb
sed -i "0,/ S   ???     1/s/ S   ???     1/ S   FEV A 502/g" pdb
sed -i "0,/ S   ???     1/s/ S   ???     1/ S   FEV A 502/g" pdb
sed -i "0,/FE   ???     1/s/FE   ???     1/FE   FEV A 502/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   FEV A 502/g" pdb
sed -i "0,/FE   ???     1/s/FE   ???     1/FE   FEV A 502/g" pdb
sed -i "0,/ S   ???     1/s/ S   ???     1/ S   FEV A 502/g" pdb
sed -i "0,/ S   ???     1/s/ S   ???     1/ S   FEV A 502/g" pdb
sed -i "0,/FE   ???     1/s/FE   ???     1/FE   FEV A 502/g" pdb
sed -i "0,/FE   ???     1/s/FE   ???     1/FE   FEV A 502/g" pdb
sed -i "0,/FE   ???     1/s/FE   ???     1/FE   FEV A 502/g" pdb
sed -i "0,/ S   ???     1/s/ S   ???     1/ S   FEV A 502/g" pdb
sed -i "0,/ S   ???     1/s/ S   ???     1/ S   FEV A 502/g" pdb
sed -i "0,/ S   ???     1/s/ S   ???     1/ S   FEV A 502/g" pdb
sed -i "0,/ V   ???     1/s/ V   ???     1/ V   FEV A 502/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   CO3 A 519/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   CO3 A 519/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   CO3 A 519/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   CO3 A 519/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   CO3 A 519/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   CO3 A 519/g" pdb

