#!/bin/bash
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A  96/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ARG A  96/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A  96/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A  96/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   ARG A  96/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A  96/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ARG A  96/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   ARG A  96/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A  96/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A  96/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   ARG A  96/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A  96/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A  96/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   CYS A 275/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   CYS A 275/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   CYS A 275/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   CYS A 275/g" pdb
sed -i "0,/ S   ???     1/s/ S   ???     1/ S   CYS A 275/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 359/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ARG A 359/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 359/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 359/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   ARG A 359/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 359/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ARG A 359/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   ARG A 359/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 359/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 359/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   ARG A 359/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 359/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ARG A 359/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   HIS A 442/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   HIS A 442/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   HIS A 442/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   HIS A 442/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   HIS A 442/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   HIS A 442/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   HIS A 442/g" pdb
sed -i "0,/ N   ???     1/s/ N   ???     1/ N   HIS A 442/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   HIS A 442/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ H   ???     1/s/ H   ???     1/ H   ACH A 501/g" pdb
sed -i "0,/ C   ???     1/s/ C   ???     1/ C   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
sed -i "0,/ O   ???     1/s/ O   ???     1/ O   ACH A 501/g" pdb
